## Analyse characteristics of Herro reads

In [9]:
library(tidyverse)
library(ggplot2)

In [10]:
f1 <- "/mnt/storage3b/projects/no_ngsd/ahthapp1_T2T_ONT/data/bamstats/mapped/TUE_02/TUE_02.HQ_combined.maxx_20x/bamstats.txt"
dt <- read_tsv(f1)

Rows: 2228910 Columns: 23
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (4): name, sample_name, ref, direction
dbl (17): coverage, ref_coverage, qstart, qend, rstart, rend, aligned_ref_le...
lgl  (2): runid, start_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [18]:
dt_a <- dt %>%
    mutate(type = if_else(str_detect(name, ";"), "duplex", "herro"))

dt_a %>% head

  name
1 7f1088c9-6544-4353-ab05-c205aa01fab9
2 94d984a0-2b01-44c0-909a-9c5c5032fe3d
3 8c941a34-9e37-4bd7-ae03-486557b48c6e;79fd22ae-3899-4e9d-b1f9-92324ada522d
4 7c0860e1-5a00-48f0-9091-6e45643fcd43;3c4b1a02-58e8-48cc-8149-192ecc9b6fbf
5 3da95f49-6fce-486a-92d3-f1950b37b126;24cfb8fe-47df-40f6-9b0d-79fc8b730c57
6 4a4b9888-bbc9-4b7e-b44a-015e738e8618;72904f7f-d117-498d-9975-55095c47264c
  runid sample_name                        ref  coverage ref_coverage qstart
1 NA    TUE_02/TUE_02.HQ_combined.maxx_20x chr1  98.6077 0.0587       1944
2 NA    TUE_02/TUE_02.HQ_combined.maxx_20x chr1  95.1183 0.0616       7932
3 NA    TUE_02/TUE_02.HQ_combined.maxx_20x chr1  99.8558 0.0054          0
4 NA    TUE_02/TUE_02.HQ_combined.maxx_20x chr1  99.8737 0.0089          0
5 NA    TUE_02/TUE_02.HQ_combined.maxx_20x chr1  99.7804 0.0053          0
6 NA    TUE_02/TUE_02.HQ_combined.maxx_20x chr1 100.0000 0.0060          0
  qend   rstart rend   ⋯ mean_quality start_time match  ins  del  sub iden
1 139977     1  145914 ⋯ 33.00        NA         136002 2031 9911 756 99.44
2 162525  2709  155627 ⋯ 33.00        NA         146035 8558 6883 729 99.50
3  13154  4361   17854 ⋯ 32.50        NA          13138   16  355  58 99.56
4  22150  5816   27950 ⋯ 19.05        NA          21730  420  404 294 98.65
5  13178 10213   23400 ⋯ 31.16        NA          13177    1   10  42 99.68
6  15748 11785   26733 ⋯ 30.36        NA          14915  833   33  89 99.40
  acc   duplex type
1 91.42 0      herro
2 89.99 0      herro
3 96.82 0      duplex
4 95.04 0      duplex
5 99.60 0      duplex
6 93.95 0      duplex

In [23]:
summary <- dt_a %>%
    group_by(type) %>%
    summarise(count = n(), across(everything(), median, na.rm = TRUE)) %>%
    select(type, count, read_length, aligned_ref_len,  match, ins, del, sub, iden, acc )
summary

Warning message:
“There were 8 warnings in `summarise()`.
The first warning was:
ℹ In argument: `across(everything(), median, na.rm = TRUE)`.
ℹ In group 1: `type = "duplex"`.
Caused by warning in `mean.default()`:
! argument is not numeric or logical: returning NA
ℹ Run `dplyr::last_dplyr_warnings()` to see the 7 remaining warnings.”

  type   count   read_length aligned_ref_len match   ins del sub iden  acc
1 duplex 1666562 12050       11966           11905.0  6   8   8  99.91 99.76
2 herro   562348 98595       98303           97561.5 43  49  87  99.92 99.81

In [26]:
library(knitr)
library(kableExtra)

kable(summary, format = "markdown", table.attr = "style='width:100%;'") %>%
    kable_styling(full_width = FALSE, position = "left")

<table class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:left;"> type </th>
   <th style="text-align:right;"> count </th>
   <th style="text-align:right;"> read_length </th>
   <th style="text-align:right;"> aligned_ref_len </th>
   <th style="text-align:right;"> match </th>
   <th style="text-align:right;"> ins </th>
   <th style="text-align:right;"> del </th>
   <th style="text-align:right;"> sub </th>
   <th style="text-align:right;"> iden </th>
   <th style="text-align:right;"> acc </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> duplex </td>
   <td style="text-align:right;"> 1666562 </td>
   <td style="text-align:right;"> 12050 </td>
   <td style="text-align:right;"> 11966 </td>
   <td style="text-align:right;"> 11905.0 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 99.91 </td>
   <td style="text-align:right;"> 99.76 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> herro </td>
   <td style="text-align:right;"> 562348 </td>
   <td style="text-align:right;"> 98595 </td>
   <td style="text-align:right;"> 98303 </td>
   <td style="text-align:right;"> 97561.5 </td>
   <td style="text-align:right;"> 43 </td>
   <td style="text-align:right;"> 49 </td>
   <td style="text-align:right;"> 87 </td>
   <td style="text-align:right;"> 99.92 </td>
   <td style="text-align:right;"> 99.81 </td>
  </tr>
</tbody>
</table>