# PLot QC improvement with added FC

In [2]:
library(tidyverse)
library(ggplot2)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [40]:
qc_asm <- read_tsv("../../assembly/qc/qc_flowcells.tsv", col_type = 'cdccc')
head(qc_asm)

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”

  metric                                                    value
1 Number of mapped sequences                                     19122
2 Number of primary alignments                                   45269
3 Number of secondary alignments                                 34659
4 Number of primary alignments with >65535 CIGAR operations          0
5 Number of bases in mapped sequences                       6685275250
6 Number of mapped bases                                    6642871159
  haplotype asm_method      asm_name    source
1 NA        unphased_verkko TUE_02_01UL stat
2 NA        unphased_verkko TUE_02_01UL stat
3 NA        unphased_verkko TUE_02_01UL stat
4 NA        unphased_verkko TUE_02_01UL stat
5 NA        unphased_verkko TUE_02_01UL stat
6 NA        unphased_verkko TUE_02_01UL stat

In [41]:
n_UL = c(1,2,3,4,5,6)
n_DX = c(0,1,2)
samples = c("TUE_02")

In [42]:
combinations <- as_tibble(expand.grid("n_UL" = n_UL, "n_DX" = n_DX, "sample" = samples)) %>%
    mutate(asm_name = ifelse(n_DX == 0,
        paste0(sample,  "_", str_pad(n_UL, 2, pad = 0), "UL"),
        paste0(sample,  "_", str_pad(n_UL, 2, pad = 0), "UL", "_", str_pad(n_DX, 2, pad = "0"), "DX")))

In [43]:
dt <- inner_join(
  combinations,
  qc_asm,
  by = join_by("asm_name"),
)

head(dt)

  n_UL n_DX sample asm_name
1 1    0    TUE_02 TUE_02_01UL
2 1    0    TUE_02 TUE_02_01UL
3 1    0    TUE_02 TUE_02_01UL
4 1    0    TUE_02 TUE_02_01UL
5 1    0    TUE_02 TUE_02_01UL
6 1    0    TUE_02 TUE_02_01UL
  metric                                                    value
1 Number of mapped sequences                                     19122
2 Number of primary alignments                                   45269
3 Number of secondary alignments                                 34659
4 Number of primary alignments with >65535 CIGAR operations          0
5 Number of bases in mapped sequences                       6685275250
6 Number of mapped bases                                    6642871159
  haplotype asm_method      source
1 NA        unphased_verkko stat
2 NA        unphased_verkko stat
3 NA        unphased_verkko stat
4 NA        unphased_verkko stat
5 NA        unphased_verkko stat
6 NA        unphased_verkko stat

In [45]:
source("../scripts/13_process_assembly_qc.R")

dt_processed <- process_qc_table(dt)b

In [47]:
head(dt_processed)

  n_UL n_DX sample asm_name    metric                          value
1 1    0    TUE_02 TUE_02_01UL Assembly Length                 6.685275e+09
2 1    0    TUE_02 TUE_02_01UL % of Ref covered by Assembly    9.599000e-01
3 1    0    TUE_02 TUE_02_01UL % of Ref duplicated in Assembly 9.024000e-01
4 1    0    TUE_02 TUE_02_01UL % of Assembly covered by Ref    9.705000e-01
5 1    0    TUE_02 TUE_02_01UL NG75                            1.274297e+06
6 1    0    TUE_02 TUE_02_01UL NG50                            1.767315e+06
  haplotype asm_method      source
1 NA        unphased_verkko asmstat
2 NA        unphased_verkko asmstat
3 NA        unphased_verkko asmstat
4 NA        unphased_verkko asmstat
5 NA        unphased_verkko asmstat
6 NA        unphased_verkko asmstat