# Figures

In [9]:
library(tidyverse)

## Assembly QC

In [10]:
hprc <- read_tsv("../../doc/tables/qc_hprc_table.tsv", show_col_types = F ) %>% 
    mutate(source = "hprc")
samples <- read_tsv("../../doc/tables/qc_samples_table.tsv", show_col_types = F) %>%
    mutate(source = "samples")


dt_qc <- bind_rows(hprc, samples) %>%
    filter(haplotype != "both") %>%
    filter(!(metric %in% c("qv")))
head(dt_qc)
tail(dt_qc)

  metric      value        haplotype  asm_method  asm_name source chromosome
1 length      2.947895e+09 haplotype1 phased_hprc HG002    hprc   NA
2 ref_covered 9.075000e-01 haplotype1 phased_hprc HG002    hprc   NA
3 asm_covered 9.653000e-01 haplotype1 phased_hprc HG002    hprc   NA
4 length      3.051530e+09 haplotype2 phased_hprc HG002    hprc   NA
5 ref_covered 9.415000e-01 haplotype2 phased_hprc HG002    hprc   NA
6 asm_covered 9.686000e-01 haplotype2 phased_hprc HG002    hprc   NA

  metric value      haplotype  asm_method    asm_name source  chromosome
1 MSC    0.05221773 haplotype1 phased_verkko T2T17    samples NA
2 MSC    0.01556011 haplotype2 phased_verkko T2T17    samples NA
3 MSC    0.05290991 haplotype1 phased_verkko T2T18    samples NA
4 MSC    0.01533861 haplotype2 phased_verkko T2T18    samples NA
5 MSC    0.05321446 haplotype1 phased_verkko T2T19    samples NA
6 MSC    0.01619691 haplotype2 phased_verkko T2T19    samples NA

In [11]:
p_qc_beesplot <- ggplot(dt_qc, aes(x = haplotype, y = value, fill = source)) +
    geom_jitter(width = 0.2, height = 0, alpha = 0.7, shape = 21, size = 1.5, colour = "grey20") +
    facet_wrap(~metric, scales = "free") +
    theme_classic()

ggsave("../../doc/figures/qc_beesplot.png", p_qc_beesplot, width = 16*0.7, height = 9*0.7)

## Chromosome plots